version: '2'
services:
    web:
        build: ./docker/apache-php
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        links:
            - db
    nfldb:
        build: ./docker/nfldb
        depends_on:
            - db
        links:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: nfldb
            POSTGRES_USER: nfldb

# apache-php:
#     build: ./apache-php/
#     ports:
#         - 80:80
#         - 443:443
#     volumes_from:
#         - app
#     links:
#         - db
#
# app:
#     image: httpd:2.4
#     volumes:
#         - .:/var/www/html
#     command: "true"
#
# db:
#     image: postgres
#     volumes_from:
#         - data
#     environment:
#         POSTGRES_PASSWORD: nfldb
#         POSTGRES_USER: nfldb
#
# data:
#     image: postgres
#     volumes:
#         - /var/lib/postgresql/data
#     command: "true"
#
# phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     ports:
#         - 8080:80
#     links:
#         - db
#     environment:
#         PMA_HOST: postgres
#         PMA_USER: nfldb
#         PMA_PASSWORD: nfldb
